name: 测试获取输入

### 以下内容请保持不变 (修改 环境变量设置 中的信息)
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      src_url:
        description: '固件源地址'
        default: ''
### END

env:
# 设备名称 (可在 README 中找到获取方法)
   
# 源码仓库:分支
  DEFAULT_SOURCE: ${{ github.event.inputs.src_url }}
  
  
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    

    - name: 输出获取的数据
      run: |         
        echo -e "输入的地址源: $DEFAULT_SOURCE"
     
